language: node_js

node_js:
  - 7

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn test -- --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - yarn run export
  - touch out/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out/
  repo: dig-its/dig-its.github.io
  target_branch: master
  project_name: dig-its.github.io
  edge: # This fixes temp deploy problem (see https://github.com/travis-ci/travis-ci/issues/9312)
    branch: v1.8.47

notifications:
  email:
    recipients:
      - verheyen.koen@gmail.com
    on_success: never
    on_failure: always